/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IslandIslandIdRouteImport } from './routes/island.$islandId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IslandIslandIdRoute = IslandIslandIdRouteImport.update({
  id: '/island/$islandId',
  path: '/island/$islandId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/island/$islandId': typeof IslandIslandIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/island/$islandId': typeof IslandIslandIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/island/$islandId': typeof IslandIslandIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/island/$islandId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/island/$islandId'
  id: '__root__' | '/' | '/island/$islandId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IslandIslandIdRoute: typeof IslandIslandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/island/$islandId': {
      id: '/island/$islandId'
      path: '/island/$islandId'
      fullPath: '/island/$islandId'
      preLoaderRoute: typeof IslandIslandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IslandIslandIdRoute: IslandIslandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
